//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hbms.Mes.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JQueryGantt
    {
        public string id { get; set; }
        public string name { get; set; }
        public Nullable<int> progress { get; set; }
        public Nullable<bool> progressByWorklog { get; set; }
        public Nullable<int> relevance { get; set; }
        public string type { get; set; }
        public string typeId { get; set; }
        public string description { get; set; }
        public string code { get; set; }
        public Nullable<int> level { get; set; }
        public string status { get; set; }
        public string depends { get; set; }
        public Nullable<bool> canWrite { get; set; }
        public string start { get; set; }
        public Nullable<int> duration { get; set; }
        public string end { get; set; }
        public Nullable<bool> startIsMilestone { get; set; }
        public Nullable<bool> endIsMilestone { get; set; }
        public Nullable<bool> collapsed { get; set; }
        public Nullable<bool> hasChild { get; set; }
        public string assigs { get; set; }
    }
}
