//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hbms.Mes.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MK_App_DTImg
    {
        public string F_Id { get; set; }
        public string F_Des { get; set; }
        public string F_FileName { get; set; }
        public Nullable<int> F_EnabledMark { get; set; }
        public Nullable<int> F_SortCode { get; set; }
    }
}
